### ISSUE TITLE
mac build JoltViewer got metal error

### ISSUE THREAD

**Issue by kkpattern** [jrouwe/JoltPhysics#1452]
Thanks for this awesome project. When I run JoltViewer on the macos platform I got following error:

```
Fatal Error: Metal error returned: library not found
Program ended with exit code: 1
```

I also got XCode complains that the return type of `acceptsFirstResponder` should be `BOOL` instead of `bool`.

The XCode version is 15.2.
The Jolt commit is 4dd129f62271d1675b5cdd3baf24214a773016ab

Should I upgrade to XCode 16?

**Comment by jrouwe** [comment]
I'm using XCode 16 indeed, but I'd prefer it if it also ran on XCode 15. 

I fixed the return types in https://github.com/jrouwe/JoltPhysics/commit/74b5814941e2470a73ef4c70d3892668ad8186bd

W.r.t. the Metal error you're getting: Currently JoltViewer assumes that the 'current path' contains the Assets folder. If you run from XCode, this should be the case, but if you run otherwise (e.g. from the terminal) then it is likely it is not. I'm still working on embedding the assets in the application bundle so that that won't be needed anymore.

**Comment by kkpattern** [comment]
I run the JoltView from the XCode but still get the error. I can see that the Assets folder is already copied beside the JoltViewer.app. Maybe XCode 15 has a different 'working directory' setting when running the app?

**Comment by jrouwe** [comment]
Perhaps. Can you check if there's a way to override the working directory in XCode? Otherwise you should be able to run it from the terminal. Does the Samples app work or does it give the same error?

**Comment by kkpattern** [comment]
I changed the working directory to the root directory of Jolt in the XCode scheme option. Now, I can successfully run both JoltViewer and Samples.

**Comment by jrouwe** [comment]
The files should now be added to the application bundle properly, so the working directory shouldn't matter anymore.
