### ISSUE TITLE
Acceleration problem with sloped suspension

### ISSUE THREAD

**Issue by Ono-Sendai** [jrouwe/JoltPhysics#455]
I'm working on bike physics.  When I create a bike with a front wheel where the suspension direction is not vertical. and where the rear wheel suspension is vertical, the bike accelerates forwards by itself.

See this video - in it I am not pressing forwards/throttle, the bike is accelerating by itself.  I brake half way thru the video and then release the brake.
https://www.youtube.com/watch?v=1aKQ4dTFIcw

for front wheel I have:

`front_wheel->mDirection = JPH::Vec3(0,-0.5,-1).Normalized();`

and for the back wheel

`rear_wheel->mDirection = JPH::Vec3(0,0,-1).Normalized();`

The bike is kept upright by the old PitchRoll constraint:

`vehicle.mMaxPitchRollAngle = JPH::DegreesToRadians(5.0f);`

Cheers,
  Nick

**Comment by jrouwe** [comment]
Non vertical suspension is something that I never tried (or even considered as something you'd want) :)

I created a fix for the biggest issue on https://github.com/jrouwe/JoltPhysics/tree/bugfix/vehicle_suspension but there are several issues that remain:
* The wheels sink into the ground because the wheel collision test does not consider the size of the wheels (this I can easily fix)
* You would want the wheels to collide against vertical walls in this case, which is turned off by default because it can generate large unwanted forces if you drive over small rubble (not sure how I'm going to fix that)

Anyway it needs some more investigation.

**Comment by jrouwe** [comment]
Hello,

I've played around with it some more (and updated the branch above) and created a motorcycle demo (not finished).

Playing around with this makes me believe that it is not the pitch/roll constraint that needs updating, but I think external forces need to be applied to keep the bike upright / make it lean in the right direction when cornering (a PID controller?).

Did you continue to work on this? And if so, how did you fix leaning in corners?

**Comment by Ono-Sendai** [comment]
Hi Jorrit,
Yes I have done some work on it.  I did try separating the constraint into pitch and roll constraints, which does kind of work, but runs in the usual issue with Euler angles - indeterminate roll when the bike is pitched straight up, ambiguities between pitch and roll etc. 

I tried making the bike lean when going around corners by changing the target roll angle, so that the lateral friction force on the wheels is balanced by the reaction force from the ground (balancing torques).  The issue there is the constraint rotates around the bike centre of mass (I think), whereas we really want to constrain rotation around the wheel contact points with the ground.  I'm not sure if Jolt has this kind of constraint.  This results in the bike tires 'skipping' sideways on the ground.  This can be ameliorated by smoothing the target roll angle - resulting in something that works alright.

An alternative would be trying this without a roll constraint, maybe hacking lateral forces applied on the upper part of the bike, to get the desired roll angle.  Haven't tried that much yet.

**Comment by Ono-Sendai** [comment]
Here's a vid where I use the target roll angle technique described above: https://twitter.com/SubstrataVr/status/1635150324909608961

**Comment by Ono-Sendai** [comment]
Trying out your vehicle suspension fix branch, get this:

https://www.youtube.com/watch?v=ZgD8ETvadRI

Forwards/backwards acceleration is fixed, but getting some lateral drift.

**Comment by Ono-Sendai** [comment]
VehicleCollisionTesterCastShape looks good, casting a small sphere was leading to problems I think.

**Comment by Ono-Sendai** [comment]
Here are some issues present in the branch:

weird oscillation with front_wheel->mSuspensionDamping = 0.0f:
looks like some kind of bug because the suspension length seems to change discontinuously. 
https://youtu.be/be9L_UjA4Vk

Oscillation at high speed:  (this is with the default mSuspensionDamping)
https://youtu.be/BHmpiTbzQh4

**Comment by Ono-Sendai** [comment]
I agree external forces using some kind of PID controller to make the bike upright / leaning into corners would be the nicest approach.

**Comment by Ono-Sendai** [comment]
Here's a test using a PID controller for roll:

https://www.youtube.com/watch?v=A9WZHCH4ABE

Well really it's a PD controller - e.g. just using roll error and droll_error / dt.

It seems to work alright, but looks like it suffers from the class PID side-effects such as overshoot, resulting in a visible wobble.

**Comment by jrouwe** [comment]
> VehicleCollisionTesterCastShape looks good, casting a small sphere was leading to problems I think.

You're not getting lateral movement anymore with this? In any case, the calculations of the new suspension are better but wrong as well, the suspension spring now operates in the direction of the contact normal, which means it will be equally strong when trying to push the wheel sideways as up/down. I'll try to correct that.

B.t.w. I'm planning to change it to a VehicleCollisionTesterCastCylinder and I'll add steering to it too.

It looks like you have much more time than I have to work on this. I'm still struggling to set the basic parameters for the bike and to get the right dimensions. If you can share anything on that / can share how you calculated the target angle / PD controller + its coefficients then that would help greatly (if you don't mind this possibly ending up in the demo that is).

**Comment by jrouwe** [comment]
> weird oscillation with front_wheel->mSuspensionDamping = 0.0f:
> looks like some kind of bug because the suspension length seems to change discontinuously.

Just tried this on the MotorcycleTest (latest version) and I don't see any issues there. The suspension becomes very wobbly as expected, but I see no discontinuity.

VehicleCollisionTesterCastCylinder has been made and I'm merging it in master with #472 as it seems to improve the car demo a lot too.

**Comment by Ono-Sendai** [comment]
One thing that would be nice for bikes is if we can specify an axis around which the steering of the front wheel rotates.  Currently it seems to be the vehicle up vector, as opposed to say the suspension direction.

On real bikes I think the steering axis is the front suspension direction, which is not vertical.

See 
https://youtu.be/jQ4pP9mQPtQ

**Comment by Ono-Sendai** [comment]
> It looks like you have much more time than I have to work on this. I'm still struggling to set the basic parameters for the bike and to get the right dimensions. If you can share anything on that / can share how you calculated the target angle / PD controller + its coefficients then that would help greatly (if you don't mind this possibly ending up in the demo that is).

Sure, will clean up and paste some source code somewhere.

**Comment by jrouwe** [comment]
> On real bikes I think the steering axis is the front suspension direction, which is not vertical.

Sure, I'll make that possible.

**Comment by Ono-Sendai** [comment]
Generally I'm getting better results with a roll constraint instead of a PID controller.  Not getting wobble or severe oscillations that PID was having sometimes.

https://youtu.be/AKXnbAKBj9U

The blue arrow shows the (unsmoothed) desired roll angle.

I am using trunk branch and vertical suspension in this vid.

There is a problem with the bike getting out of  control and spinning around.  I'm not sure if that's due to the roll constraint.

**Comment by Ono-Sendai** [comment]
Ok looks like the loss of control at high speeds is due to the tilting of the roll constraint.
Here is without any tilting (so just constrained roll to 1 degree from vertical):

https://youtu.be/_Ut5NkupT2o

I think the issue might be the roll constraint lifting the wheels off the ground, since it applies torque to the object, right?

Can we make a rotation constraint that rotates around a line that is not the centre of mass of the body?  (the line would be the line from rear wheel contact point to front wheel contact point)

**Comment by jrouwe** [comment]
Thanks, I downloaded them! It will take a couple of days before I have time to work on this.

> I think the issue might be the roll constraint lifting the wheels off the ground, since it applies torque to the object, right?

The roll constraint applies torque to the center of mass, so I guess it can indeed reduce the pressure of the wheels on the ground.

> Can we make a rotation constraint that rotates around a line that is not the centre of mass of the body? (the line would be the line from rear wheel contact point to front wheel contact point)

Yes, but there is no constraint part for that (yet). I'm not sure if this will work though (it may prevent the bike from sliding entirely as it will constrain motion around an axis). Need to think about it.

**Comment by jrouwe** [comment]
Small update from my side:

I have implemented a dampened angular spring to make the bike lean in the desired direction on [the branch](https://github.com/jrouwe/JoltPhysics/tree/bugfix/vehicle_suspension). I first started with atan(lateral friction force / gravity * mass) just like you have in your code but found that the friction force jitters quite a lot when driving so I switched to atan(velocity^2 / gravity * turn radius) which gives a much more consistent angle.

I am seeing the same behavior that the wheels are lifted from the ground when you quickly switch between going from left to right. I think you're right that this is because of the angular momentum that is applied. I started on the idea of rotating around the axis that goes through both wheel contact points but didn't get it to work better yet.

My main realization was that when you use the arrow keys to control the bike, it's very hard to control the velocity of the bike. This means that in turns it is almost impossible to not go too fast. If you then use the full steering angle, the bike is just going to spin out, so I implemented a system where you can specify a max lean angle that is acceptable for the bike (separate from the hard limit by the roll/pitch constraint) and it will use the current velocity to calculate the max steering angle that will make you lean over by this max angle. This means that the faster you go, the less you steer and that makes the bike much more stable. It does mean that you lean over quite a lot while going relatively slow because the max steer angle at this velocity requires a large lean angle. I think I'm going to fix this by making it possible to specify a max lean angle vs speed curve so you can limit the max lean angle to higher velocities.

My todo list:

- Fix suspension spring when suspension is under an angle. Spring operates in the direction of the ground normal but should operate in direction of suspension.
- It should be possible to make the wheel steer using a different axis (e.g. suspension axis) than the vehicle up axis.
- The lean angle / angular impulse system assumes that the bike is horizontal, needs to be fixed for sloped terrain.
- Fix angular impulse lifting the wheels off the floor.
- Lean angle is very large when driving at low speeds, make max lean angle velocity dependent.
- Investigate solution where making a turn is initiated by shifting the driver mass / by counter steering which makes the bike lean followed by the actual steering towards the turn.

I think the last point would make the bike behave much more natural, but is probably also really complex to implement.

**Comment by Ono-Sendai** [comment]
Sounds interesting.  One problem that springs to mind with using turn radius is that you won't be able to do cool sideways slides, like in https://www.youtube.com/watch?v=A9hCzjBc7Q4
In these slides the turn radius is infinite (e.g. the front wheel is straight), but there should still be a tilt.

**Comment by Ono-Sendai** [comment]
Regarding spinning out at high speed due to steering changes, one idea could be do decrease the steering angle based on increased velocity.   E.g. steering angle factor = 1 / (bike_velocity - constant) or something.

**Comment by Ono-Sendai** [comment]
By the way, the initial reported problem with sloped suspension causing acceleration is not just a problem with the angle of the suspension vector, but also occurs if the front and back suspension have different lengths (and are both vertical).

**Comment by jrouwe** [comment]
> One problem that springs to mind with using turn radius is that you won't be able to do cool sideways slides

True, although I'm not sure how doable it is in real life to make slides without steering.

> By the way, the initial reported problem with sloped suspension causing acceleration is not just a problem with the angle of the suspension vector, but also occurs if the front and back suspension have different lengths (and are both vertical).

Yes that makes sense. When the suspension would make the vehicle body slope up or down it will apply an incorrect force.

**Comment by Ono-Sendai** [comment]
It's hard to do a very nice controlled slide in a video game, but it's pretty easy to slide the back wheel out with a slight nudge of the front steering: https://www.youtube.com/watch?v=YvFzGGOYA3k

**Comment by jrouwe** [comment]
I just merged support for non-vertical suspensions in 172a99c718bded5faa169ac440517286684fa2f0.

The motor cycle test code has moved to https://github.com/jrouwe/JoltPhysics/tree/feature/motorcycle

Next up is supporting steering axis != suspension axis.

**Comment by Ono-Sendai** [comment]
Great, will try it out soon!

**Comment by Ono-Sendai** [comment]
Testing, looking good so far.
I think VehicleConstraint::GetWheelLocalTransform needs to be updated:

Vec3 local_forward = Quat::sRotation(mUp, wheel->mSteerAngle) * mForward;

This should be a rotation around the suspension direction now instead of mUp presumably.

**Comment by jrouwe** [comment]
Yes, that's what I'm working on.

**Comment by Ono-Sendai** [comment]
currently steering axis = vehicle up axis though, not suspension axis.

**Comment by jrouwe** [comment]
I just merged a change to allow specifying the steering axis (for changes needed see: a41028cc2e3eded9a9176a98887b05d545f00bb1)

**Comment by Ono-Sendai** [comment]
Hi,
The biggest issue I'm still seeing is a tendency to enter a sideways slide when steering at higher speeds (e.g. above 200 km/h), and sometimes at lower speeds.  Are you experiencing this also?

In this video, providing a slight non-zero steering input results in sliding out:

https://youtu.be/gUULw31l0d0

**Comment by jrouwe** [comment]
I haven't tried without leaning code but I'm seeing lots of sliding. I'm trying to get the leaning to work properly now, this should give extra pressure on the wheels so extra grip.

**Comment by jrouwe** [comment]
I've merged in a first version of the motorcycle controller into the master branch.

* I am now applying a force to the COM of the body to counter the velocity change on the wheels, this makes the wheels much less likely to leave the ground
* This also made it possible to switch back to using the contact impulse for determining the lean angle as the angular spring now causes much less force on the tires (this was the main cause that the lean angle was very jittery before)
* The convex radius of the cylinder is now half the width of the tire so we get a perfectly round wheel, which also helps reducing jitter in the contact normal

The main issue now seems to be braking in corners especially in combination with sudden steering. I reduced the amount of braking with lean angle to alleviate some of this, but I think the steering velocity will probably also need to be adjusted to get better handling. This is very game dependent though, so I'm not sure if I should make this part of the motorcycle controller.

**Comment by Ono-Sendai** [comment]
Cool.
I tried reducing the steering velocity right down but was still getting spin/sliding out effects.
Will try this new controller.

**Comment by Ono-Sendai** [comment]
Trying out motorcycle controler: The direction of movement seems wrong - forwards input is making the bike go backwards.

**Comment by Ono-Sendai** [comment]
The new motorcycle controller seems quite unstable in some circumstances, I think maybe when the time step size (dt) gets larger.
See
https://youtu.be/od0vwSr6s1c
and
https://www.youtube.com/watch?v=QLSjNQjJPwc
In the second video the instability is triggered just by alt-tabbing, which presumably only affects the time step size. 
I checked the time step size is < 1/60s, usually it's running at 1/144s though, when not alt-tabbing.

**Comment by Ono-Sendai** [comment]
On the positive size, sliding out when steering is greatly reduced :)

**Comment by jrouwe** [comment]
> Trying out motorcycle controler: The direction of movement seems wrong - forwards input is making the bike go backwards.

This controller doesn't change anything to movement direction (the controller only adds a lean spring). Have you filled in the new wheel up/forward members that was added in an earlier change?

> In the second video the instability is triggered just by alt-tabbing, which presumably only affects the time step size.

Running physics with a variable time step is very dangerous (as many calculations are non-linear with respect to the time step) and you should definitively not pass a dt bigger than 1/60th of a second.

> The new motorcycle controller seems quite unstable in some circumstances

Looking at the videos, I think you have to tune mLeanSpringConstant and mLeanSpringDamping to the mass of your bike. It looks like especially the spring constant is way too big for your bike.

**Comment by Ono-Sendai** [comment]
Hi Jorrit,
Ok I have the bike going the right way now :), and reduced the spring constants to make the sim stable.

The biggest issue I am running into now is the bike falling on its side when going over relatively low obstacles, see for example this vid:

https://www.youtube.com/watch?v=JeiVdNMJ9LM

The bike hits a 5cm step.  If you slow it right down (playback speed 0.25) you can actually see that when the back wheel hits the step, there is a large leftwards impulse applied.   (Am visualising GetLateralLambda() with the yellow arrows).
I think this is what causes the bike to slide left and over on to its side.   Any ideas what is causing this?

**Comment by Ono-Sendai** [comment]
Another thing I have noticed is that the leaning is nowhere near the max lean angle.

See https://www.youtube.com/watch?v=3adfT8pixlE

I have set 
```controller_settings->mMaxLeanAngle = JPH::DegreesToRadians(60.f);```
As you can see, the lean angle is much less than 60 degrees, and it also appears to decrease as speed increases.

I observed similar behaviour to this with my lean constraint where I set the max steering based on max lean angle - at higher speeds the resulting lean angle was much less than the max lean angle.  I'm not sure why this is though!
(possibly the spring constants have some effect but I think that's not the full story)

**Comment by jrouwe** [comment]
> there is a large leftwards impulse applied. (Am visualising GetLateralLambda() with the yellow arrows).
I think this is what causes the bike to slide left and over on to its side. Any ideas what is causing this?

My guess is that this is caused by the contact normal being horizontal. Can you try setting:

```
outContactNormal = Vec3::sAxisY(); //collector.mContactNormal;
````

(or whatever axis is up in your world) in VehicleCollisionTesterCastCylinder::Collide? If this fixes it I'm curious what normal it is returning when this happens and what shape type you're bumping into (MeshShape?).

> As you can see, the lean angle is much less than 60 degrees, and it also appears to decrease as speed increases.

This is what it looks like for me with max 60 degrees:

https://user-images.githubusercontent.com/1621693/229890345-fa458b89-24e9-4439-b009-67670d7f1718.mp4

You can see that it leans over much more than in your movie (to about 50 degrees) and the calculated target lean angle is around 60 degrees. In this case the spring is not strong enough to counter the centrifugal forces operating on the bike, if I up the spring constant to 7000 it does reach 60 degrees. Also I had to make the wheel friction much bigger because otherwise the bike will just slip which results in a much lower contact force and therefore a lower lean angle (about 45 degrees).

**Comment by Ono-Sendai** [comment]
Regarding the lean angle, can you replicate that the calculated target angle drops at higher speeds?  For me it drops to around 40 degrees at 300km/h.  (should be 60).

**Comment by Ono-Sendai** [comment]
![stationary on slope](https://user-images.githubusercontent.com/30285/230089284-3a0b3221-80ea-4307-9b02-ee347b8ed9b1.PNG)

By the way this is how the bike looks while stationary on a sloping surface.   Obviously it should be vertical :)

**Comment by jrouwe** [comment]
> Regarding the lean angle, can you replicate that the calculated target angle drops at higher speeds? For me it drops to around 40 degrees at 300km/h. (should be 60). And actual lean angle is only 20 degrees.

My bike maxes out at around 215 km/h but it maintains its lean angle (when I make the adjustments as described above):

![image](https://user-images.githubusercontent.com/1621693/230186376-eafb5637-3da2-4ace-9c02-60649ae419d9.png)

But cornering at 300 km/h is suicide, in races sharp corners seem to be made at < 150 km/h: https://photo.gp/2015/05/02/jerez-track-map-with-speed-and-gear-telemetry/. 

> By the way this is how the bike looks while stationary on a sloping surface. Obviously it should be vertical :)

Works for me:

![image](https://user-images.githubusercontent.com/1621693/230185417-0b93a8ef-1f72-461e-b636-8a1d35fbf68b.png)

My guess this is the same thing as with turns: Your spring is not powerful enough to counter gravity.

**Comment by Ono-Sendai** [comment]
An issue I noticed, where merely turning increases the speed of the bike.  I am not applying any forward input in this video:

https://youtu.be/HkoQn0TyAso

**Comment by jrouwe** [comment]
> This seems wrong, it should be (0, 0, 1), should it not?

I'm not sure what's different for you. Even on a 45 degree ramp I'm getting an almost perfect up vector (Y is up for me):

![image](https://user-images.githubusercontent.com/1621693/230711316-13f34371-b551-49ae-a372-a7ab3b86976d.png)

(note that the target_lean vector can jitter a bit, mTargetLean is the averaged version which I'm printing here)

Note that this was created by applying this diff (which basically turns on the brakes, ups the slope angle and increases lateral tire friction because otherwise the motor just slides down the slope) and pressing C in the sample application to draw the constraints:

[diff.txt](https://github.com/jrouwe/JoltPhysics/files/11182827/diff.txt)

> An issue I noticed, where merely turning increases the speed of the bike. I am not applying any forward input in this video:

This is probably caused by the angular spring. I'm guessing this can add energy to the whole system. I'm planning to work on a solution that involves counter steering instead of a spring which should hopefully fix this.

> The hit shape is a scaled shape around a box shape. The resulting box is 10cm high, with centre at z (vertical coord) = 0. (so sticking 5cm out of ground).

I'll look at this one.

**Comment by Ono-Sendai** [comment]
I'm not quite sure what's different for me either.
There's some interesting results with changing the centre of mass offsets:

no centre of mass offset:
![no COM offset](https://user-images.githubusercontent.com/30285/230728584-28bfe987-50f2-491e-bf29-c1da6db49f58.PNG)

With half-height centre of mass offset:
![with half vehicle height COM offset](https://user-images.githubusercontent.com/30285/230728612-42fc40ee-2158-4607-86b0-69701533bcb2.PNG)

I'm visualising both lateral and suspension impulses.  Note that in the top image there is almost zero lateral impulse.

**Comment by jrouwe** [comment]
I just checked what happens if the vehicle mUp != world space up. The pitch/roll limit calculation completely breaks down (fixed that in #510), but other than that I did not see any issues. On my steep slope, the motor cycle still has a target lean aligning with the y-axis. 

Shifting the COM has a big influence on the lean spring constant/damping factor that is needed but after re-tweaking I could get the cycle to point up again.

**Comment by Ono-Sendai** [comment]
One request: Can we have some way of disabling the spring/force that keeps the bike upwards, after the bike controller has been created?
The use case is for when the player dismounts the motorbike - in this case we want to keep the motorcycle constraint (we still want the wheels to be attached to the body, we still want suspension to work etc.), however since the player is not on the bike, it should not be balancing by itself.
I can hack this in by setting the spring constant to zero, but it would be cleaner and more efficient to have a way of turning it off at runtime completely.

**Comment by jrouwe** [comment]
> One request: Can we have some way of disabling the spring/force that keeps the bike upwards, after the bike controller has been created?

Sorry, I missed this comment. I've implemented it in #528.

**Comment by jrouwe** [comment]
> The biggest issue I am running into now is the bike falling on its side when going over relatively low obstacles, see for example this vid:
> https://www.youtube.com/watch?v=JeiVdNMJ9LM
> The bike hits a 5cm step. If you slow it right down (playback speed 0.25) you can actually see that when the back wheel hits the step, there is a large leftwards impulse applied. (Am visualising GetLateralLambda() with the yellow arrows).
> I think this is what causes the bike to slide left and over on to its side. Any ideas what is causing this?

I'm doing a bit of work on the bike again, I submitted #562 which seems to help with this. I added a test level with a step and added options to the motorcycle test to change the point where forces are applied to the motor bike. This seems to make things a lot more stable.

Also there is now #564 which allows you to add an integral component to the lean spring, which should help achieve the desired lean angle. It will require tweaking though.

**Comment by Ono-Sendai** [comment]
Setting mEnableSuspensionForcePoint for front and rear wheels gives very weird/wrong behaviour:
https://youtu.be/nBMaJDux2EA

**Comment by Ono-Sendai** [comment]
> 

Thanks, perfect.

**Comment by Ono-Sendai** [comment]
> > One request: Can we have some way of disabling the spring/force that keeps the bike upwards, after the bike controller has been created?
> 
> Sorry, I missed this comment. I've implemented it in #528.

Thanks, perfect.

**Comment by jrouwe** [comment]
> Setting mEnableSuspensionForcePoint for front and rear wheels gives very weird/wrong behaviour:
> https://youtu.be/nBMaJDux2EA

Did you also set the actual point? E.g.:

```
front->mSuspensionForcePoint = front->mPosition + front->mSuspensionDirection * front->mSuspensionMinLength;
```

It looks like the forces are not being applied to approximately the center of the wheel.

You can draw the positions by adding:

```
DebugRenderer::sInstance->DrawMarker(mBody->GetCenterOfMassPosition() + r1_plus_u, Color::sYellow, 1.0f);
```

After [this](https://github.com/jrouwe/JoltPhysics/blob/ad9cd403cc032bf56442803616d1081788df9d96/Jolt/Physics/Vehicle/VehicleConstraint.cpp#L369) line.

**Comment by Ono-Sendai** [comment]
Ok I tried setting the point as you said.  
Now the bike tends to skid out with even a small steering input:

https://youtu.be/6eJId3xY1io

**Comment by jrouwe** [comment]
Is there still anything needed for this ticket? If not I'll close this ticket. (I see lots of movies of you driving around the world, so it seems to be all working)

**Comment by jrouwe** [comment]
Yes, please do. This thread is getting rather long.
